version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rasplus
      MYSQL_USER: root
      MYSQL_PASSWORD: root
